version: "3.8"

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - IS_DOCKER=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=asdf
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
      - ./captured_images:/app/captured_images
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=asdf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
